/*
 * 4_migration_heuresmanuelles.sql
 * migration des collectes 2026-05-28
 */


--ALTER TABLE public.core_heuresmanuelles_1
--ALTER COLUMN id
--ADD GENERATED BY DEFAULT AS IDENTITY;


TRUNCATE TABLE public.core_heuresmanuelles RESTART IDENTITY;


INSERT INTO public.core_heuresmanuelles (
    --id,
    "date",
    heure_debut,
    heure_fin,
    motif_heures_sup,
    date_creation,
    date_modification,
    agent_id,
    presence_id
)
SELECT
    --id_old ,
    "date",
    heure_debut,
    heure_fin,
    motif_heures_sup,
    date_creation,
    date_modification,
    agent_id,
    presence_id
FROM preprod_core_heuresmanuelles;