services:
  db:
    image: postgres:17
    container_name: postgres17
    environment:
      POSTGRES_DB: bdd_regie
      POSTGRES_USER: super_user
      POSTGRES_PASSWORD: D@ta1sFeun!2026!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U super_user -d bdd_regie"]
      interval: 5s
      timeout: 5s
      retries: 10


  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django6
    command: >
      sh -c "python manage.py migrate &&
      python manage.py shell -c \"import os; from django.contrib.auth import get_user_model; U=get_user_model(); u,created=U.objects.get_or_create(username=os.environ['DJANGO_SUPERUSER_USERNAME'], defaults={'is_staff':True,'is_superuser':True,'email':os.environ.get('DJANGO_SUPERUSER_EMAIL','')}); u.is_staff=True; u.is_superuser=True; u.set_password(os.environ['DJANGO_SUPERUSER_PASSWORD']); u.save(); print('superuser ready:', u.username, 'created=', created)\" &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: django-insecure-9=*+^pc%4$$*=z_w_#79@ukj=&o*rnu31-7*-=m-ezwwwzyu8v
      DEBUG: "True"
      DB_NAME: bdd_regie
      DB_USER: super_user
      DB_PASSWORD: D@ta1sFeun!2026!
      DB_HOST: db
      DB_PORT: "5432"
    depends_on:
      db:
        condition: service_healthy


volumes:
  postgres_data:

