# Generated by Django 6.0.1 on 2026-03-24 16:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=150)),
                ('service', models.CharField(blank=True, max_length=150)),
                ('employeur', models.CharField(blank=True, max_length=150)),
                ('hds_defaut', models.TimeField(blank=True, null=True)),
                ('hfs_defaut', models.TimeField(blank=True, null=True)),
                ('echeance_permis', models.DateField(blank=True, null=True)),
                ('echeance_fco', models.DateField(blank=True, null=True)),
                ('arrivee', models.DateField(blank=True, null=True)),
                ('depart', models.DateField(blank=True, null=True)),
                ('tel', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Energie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energie', models.CharField(max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['energie'],
            },
        ),
        migrations.CreateModel(
            name='Flux',
            fields=[
                ('id_flux', models.AutoField(primary_key=True, serialize=False)),
                ('flux', models.CharField(max_length=150)),
                ('flux_long', models.CharField(max_length=255)),
                ('couleur_flux', models.CharField(blank=True, max_length=50)),
                ('archive', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['flux'],
            },
        ),
        migrations.CreateModel(
            name='PresenceMotif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pres', models.CharField(max_length=150)),
                ('presence', models.CharField(max_length=150)),
                ('jour_travail', models.FloatField()),
                ('couleur_hex_motif_presence', models.CharField(blank=True, max_length=7)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['pres', 'presence'],
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_vehicule', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('archive', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeuresManuelles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('presence', models.CharField(blank=True, max_length=150)),
                ('motif_heures_sup', models.CharField(blank=True, max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='heures_manuelles', to='core.agent')),
            ],
            options={
                'ordering': ['-date', 'agent__nom', 'agent__prenom', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Collecte',
            fields=[
                ('id_collecte', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_collecte', models.DateField(default=django.utils.timezone.localdate)),
                ('a1_hr_debut', models.TimeField(blank=True, null=True)),
                ('a1_hr_fin', models.TimeField(blank=True, null=True)),
                ('a2_hr_debut', models.TimeField(blank=True, null=True)),
                ('a2_hr_fin', models.TimeField(blank=True, null=True)),
                ('a3_hr_debut', models.TimeField(blank=True, null=True)),
                ('a3_hr_fin', models.TimeField(blank=True, null=True)),
                ('km_depart', models.FloatField(blank=True, null=True)),
                ('km_retour', models.FloatField(blank=True, null=True)),
                ('tonnage1', models.FloatField(blank=True, null=True)),
                ('tonnage2', models.FloatField(blank=True, null=True)),
                ('tonnage3', models.FloatField(blank=True, null=True)),
                ('energie_qte_1', models.FloatField(blank=True, null=True)),
                ('energie_qte_2', models.FloatField(blank=True, null=True)),
                ('energie_qte_3', models.FloatField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('id_agent_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes_agent_1', to='core.agent')),
                ('id_agent_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes_agent_2', to='core.agent')),
                ('id_agent_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes_agent_3', to='core.agent')),
                ('id_energie_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes_energie1', to='core.energie')),
                ('id_energie_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes_energie2', to='core.energie')),
                ('id_energie_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes_energie3', to='core.energie')),
                ('id_flux1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes_flux1', to='core.flux')),
                ('id_flux2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes_flux2', to='core.flux')),
                ('id_flux3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes_flux3', to='core.flux')),
                ('id_vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes', to='core.vehicule')),
            ],
            options={
                'ordering': ['-date_collecte', '-date_creation'],
            },
        ),
    ]
