# Generated by Django 6.0.1 on 2026-01-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ag', models.PositiveIntegerField(unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=150)),
                ('service', models.CharField(blank=True, max_length=150)),
                ('employeur', models.CharField(blank=True, max_length=150)),
                ('hds_defaut', models.TimeField(blank=True, null=True)),
                ('hajout_quotidien', models.TimeField(blank=True, null=True)),
                ('echeance_permis', models.DateField(blank=True, null=True)),
                ('echeance_fco', models.DateField(blank=True, null=True)),
                ('supp', models.BooleanField(default=False)),
                ('arrivee', models.DateField(blank=True, null=True)),
                ('depart', models.DateField(blank=True, null=True)),
                ('tel', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
