# Generated by Django 6.0.1 on 2026-04-20

import django.db.models.deletion
from django.db import migrations, models


def prepare_energie_fk_data(apps, schema_editor):
    Energie = apps.get_model("core", "Energie")
    Vehicule = apps.get_model("core", "Vehicule")

    # Ensure unique values for Energie.energie before adding unique constraint.
    duplicates = (
        Energie.objects.values("energie")
        .annotate(total=models.Count("id"))
        .filter(total__gt=1)
    )
    for item in duplicates:
        energie_value = item["energie"]
        ids = list(
            Energie.objects.filter(energie=energie_value)
            .order_by("id")
            .values_list("id", flat=True)
        )
        if len(ids) > 1:
            Energie.objects.filter(id__in=ids[1:]).delete()

    # Preserve existing Vehicule.energie labels by ensuring they exist in core_energie.
    vehicule_energies = (
        Vehicule.objects.exclude(energie__isnull=True)
        .exclude(energie__exact="")
        .values_list("energie", flat=True)
        .distinct()
    )
    existing_energies = set(Energie.objects.values_list("energie", flat=True))
    for energie_value in vehicule_energies:
        if energie_value not in existing_energies:
            Energie.objects.create(energie=energie_value)
            existing_energies.add(energie_value)

    # Empty string cannot satisfy FK constraint: convert to NULL.
    Vehicule.objects.filter(energie="").update(energie=None)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicule",
            name="energie",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.RunPython(prepare_energie_fk_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="energie",
            name="energie",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="vehicule",
            name="energie",
            field=models.ForeignKey(
                blank=True,
                db_column="energie",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicules",
                to="core.energie",
                to_field="energie",
            ),
        ),
    ]
