# Generated by Django 6.0.1 on 2026-04-20

import django.db.models.deletion
from django.db import migrations, models


def copy_vehicule_energie_label_to_fk(apps, schema_editor):
    Energie = apps.get_model("core", "Energie")
    Vehicule = apps.get_model("core", "Vehicule")

    energie_by_label = {
        energie_label: energie_id
        for energie_id, energie_label in Energie.objects.values_list("id", "energie")
    }

    vehicules = Vehicule.objects.exclude(energie_label__isnull=True).exclude(energie_label__exact="")
    for vehicule in vehicules.iterator():
        energie_pk = energie_by_label.get(vehicule.energie_label)
        if energie_pk is not None:
            vehicule.energie_id = energie_pk
            vehicule.save(update_fields=["energie"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_vehicule_energie_fk"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicule",
            old_name="energie",
            new_name="energie_label",
        ),
        migrations.AlterField(
            model_name="vehicule",
            name="energie_label",
            field=models.CharField(
                blank=True,
                db_column="energie",
                default=None,
                editable=False,
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="energie",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicules",
                to="core.energie",
            ),
        ),
        migrations.RunPython(copy_vehicule_energie_label_to_fk, migrations.RunPython.noop),
    ]
