# Generated by Django 6.0.1 on 2026-01-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('vehicule', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=80)),
                ('archive', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
