# Generated by Django 6.0.1 on 2026-01-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vehicule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flux',
            fields=[
                ('id_flux', models.AutoField(primary_key=True, serialize=False)),
                ('flux', models.CharField(max_length=150)),
                ('flux_long', models.CharField(max_length=255)),
                ('archive', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['flux'],
            },
        ),
    ]
