# Generated by Django 6.0.1 on 2026-04-20

from django.db import migrations


FORWARD_SQL = """
CREATE OR REPLACE VIEW stat_tournees AS (
    SELECT
        co.id_collecte,
        co.id_vehicule_id,
        ve.nom_vehicule,
        ve.type AS type_vehicule,
        co.id_itineraire_id,
        it.itineraire,
        COALESCE(co.km_retour - co.km_depart, 0) AS km_tournee,
        COALESCE(co.tonnage1, 0) + COALESCE(co.tonnage2, 0) + COALESCE(co.tonnage3, 0) AS tonnage_tournee,
        COALESCE(hr_depot_retour, TIME '12:00') - COALESCE(hr_depot_depart, TIME '05:00') AS duree_tournee,
        eg.energie,
        co.energie_qte_1 AS energie_qte_tournee
    FROM core_collecte co
    LEFT JOIN core_vehicule ve ON co.id_vehicule_id = ve.id
    LEFT JOIN core_energie eg ON ve.energie_id = eg.id
    LEFT JOIN core_itineraire it ON it.id = co.id_itineraire_id
);

CREATE OR REPLACE VIEW stat_vidages AS
WITH
tournees AS (
    SELECT * FROM stat_tournees
),
vidages AS (
    SELECT
        t.id_collecte,
        t.id_vidage,
        t.date_collecte,
        t.id_flux,
        t.tonnage
    FROM (
        SELECT
            id_collecte,
            'c' || id_collecte || 'v1' AS id_vidage,
            date_collecte,
            id_flux1_id AS id_flux,
            tonnage1 AS tonnage
        FROM core_collecte
        WHERE tonnage1 IS NOT NULL
        UNION ALL
        SELECT
            id_collecte,
            'c' || id_collecte || 'v2' AS id_vidage,
            date_collecte,
            id_flux2_id AS id_flux,
            tonnage2 AS tonnage
        FROM core_collecte
        WHERE tonnage2 IS NOT NULL
        UNION ALL
        SELECT
            id_collecte,
            'c' || id_collecte || 'v3' AS id_vidage,
            date_collecte,
            id_flux3_id AS id_flux,
            tonnage3 AS tonnage
        FROM core_collecte
        WHERE tonnage3 IS NOT NULL
    ) t
),
vidages2 AS (
    SELECT
        vi.id_collecte,
        vi.id_vidage,
        vi.date_collecte,
        vi.id_flux,
        (vi.tonnage / 1000)::numeric AS tonnage,
        tr.km_tournee,
        tr.tonnage_tournee,
        tr.energie,
        tr.energie_qte_tournee,
        tr.id_vehicule_id,
        tr.nom_vehicule,
        tr.type_vehicule,
        tr.id_itineraire_id,
        tr.itineraire,
        tr.duree_tournee,
        CASE
            WHEN NULLIF(tr.tonnage_tournee, 0) IS NULL THEN 0
            ELSE round((vi.tonnage / NULLIF(tr.tonnage_tournee, 0))::numeric, 6)
        END AS ventil
    FROM vidages vi
    LEFT JOIN tournees tr ON tr.id_collecte = vi.id_collecte
)
SELECT
    vi2.id_collecte,
    vi2.id_vidage,
    vi2.date_collecte,
    vi2.id_vehicule_id,
    vi2.nom_vehicule,
    vi2.type_vehicule,
    vi2.id_itineraire_id,
    vi2.itineraire,
    duree_tournee,
    vi2.id_flux,
    fl.flux,
    fl.couleur_flux,
    vi2.tonnage,
    round((vi2.km_tournee * vi2.ventil)::numeric, 6) AS km,
    vi2.energie,
    round((vi2.energie_qte_tournee * vi2.ventil)::numeric, 6) AS energie_qte
FROM vidages2 vi2
LEFT JOIN core_flux fl ON fl.id_flux = vi2.id_flux
ORDER BY vi2.date_collecte, fl.flux, vi2.id_collecte;
"""


REVERSE_SQL = """
CREATE OR REPLACE VIEW stat_tournees AS (
    SELECT
        co.id_collecte,
        co.id_vehicule_id,
        ve.nom_vehicule,
        ve.type AS type_vehicule,
        co.id_itineraire_id,
        it.itineraire,
        COALESCE(co.km_retour - co.km_depart, 0) AS km_tournee,
        COALESCE(co.tonnage1, 0) + COALESCE(co.tonnage2, 0) + COALESCE(co.tonnage3, 0) AS tonnage_tournee,
        COALESCE(hr_depot_retour, TIME '12:00') - COALESCE(hr_depot_depart, TIME '05:00') AS duree_tournee,
        ve.energie,
        co.energie_qte_1 AS energie_qte_tournee
    FROM core_collecte co
    LEFT JOIN core_vehicule ve ON co.id_vehicule_id = ve.id
    LEFT JOIN core_itineraire it ON it.id = co.id_itineraire_id
);

CREATE OR REPLACE VIEW stat_vidages AS
WITH
tournees AS (
    SELECT * FROM stat_tournees
),
vidages AS (
    SELECT
        t.id_collecte,
        t.id_vidage,
        t.date_collecte,
        t.id_flux,
        t.tonnage
    FROM (
        SELECT
            id_collecte,
            'c' || id_collecte || 'v1' AS id_vidage,
            date_collecte,
            id_flux1_id AS id_flux,
            tonnage1 AS tonnage
        FROM core_collecte
        WHERE tonnage1 IS NOT NULL
        UNION ALL
        SELECT
            id_collecte,
            'c' || id_collecte || 'v2' AS id_vidage,
            date_collecte,
            id_flux2_id AS id_flux,
            tonnage2 AS tonnage
        FROM core_collecte
        WHERE tonnage2 IS NOT NULL
        UNION ALL
        SELECT
            id_collecte,
            'c' || id_collecte || 'v3' AS id_vidage,
            date_collecte,
            id_flux3_id AS id_flux,
            tonnage3 AS tonnage
        FROM core_collecte
        WHERE tonnage3 IS NOT NULL
    ) t
),
vidages2 AS (
    SELECT
        vi.id_collecte,
        vi.id_vidage,
        vi.date_collecte,
        vi.id_flux,
        (vi.tonnage / 1000)::numeric AS tonnage,
        tr.km_tournee,
        tr.tonnage_tournee,
        tr.energie,
        tr.energie_qte_tournee,
        tr.id_vehicule_id,
        tr.nom_vehicule,
        tr.type_vehicule,
        tr.id_itineraire_id,
        tr.itineraire,
        tr.duree_tournee,
        CASE
            WHEN NULLIF(tr.tonnage_tournee, 0) IS NULL THEN 0
            ELSE round((vi.tonnage / NULLIF(tr.tonnage_tournee, 0))::numeric, 6)
        END AS ventil
    FROM vidages vi
    LEFT JOIN tournees tr ON tr.id_collecte = vi.id_collecte
)
SELECT
    vi2.id_collecte,
    vi2.id_vidage,
    vi2.date_collecte,
    vi2.id_vehicule_id,
    vi2.nom_vehicule,
    vi2.type_vehicule,
    vi2.id_itineraire_id,
    vi2.itineraire,
    duree_tournee,
    vi2.id_flux,
    fl.flux,
    fl.couleur_flux,
    vi2.tonnage,
    round((vi2.km_tournee * vi2.ventil)::numeric, 6) AS km,
    vi2.energie,
    round((vi2.energie_qte_tournee * vi2.ventil)::numeric, 6) AS energie_qte
FROM vidages2 vi2
LEFT JOIN core_flux fl ON fl.id_flux = vi2.id_flux
ORDER BY vi2.date_collecte, fl.flux, vi2.id_collecte;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_vehicule_energie_to_pk_fk"),
    ]

    operations = [
        migrations.RunSQL(sql=FORWARD_SQL, reverse_sql=REVERSE_SQL),
        migrations.RemoveField(
            model_name="vehicule",
            name="energie_label",
        ),
    ]
