# Generated by Django 6.0.1 on 2026-03-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_collecte_id_energie_1"),
    ]

    operations = [
        migrations.CreateModel(
            name="Itineraire",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("itineraire", models.CharField(max_length=150)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["itineraire"],
            },
        ),
    ]
