# Generated by Django 6.0.1 on 2026-03-25 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_itineraire"),
    ]

    operations = [
        migrations.AddField(
            model_name="collecte",
            name="id_itineraire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collectes",
                to="core.itineraire",
            ),
        ),
    ]
