# Generated by Django 6.0.1 on 2026-03-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_collecte_id_itineraire"),
    ]

    operations = [
        migrations.AddField(
            model_name="collecte",
            name="consignes",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="collecte",
            name="info_collecte",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="collecte",
            name="info_vehicule",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
