# Generated by Django 6.0.1 on 2026-03-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_collecte_commentaires"),
    ]

    operations = [
        migrations.AddField(
            model_name="collecte",
            name="hr_sup_debut",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collecte",
            name="hr_sup_fin",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collecte",
            name="motif_heures_sup",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
