# Generated by Django 6.0.1 on 2026-03-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_collecte_heures_sup_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="collecte",
            name="hr_depot_depart",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collecte",
            name="hr_depot_retour",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
