# Generated by Django 6.0.1 on 2026-01-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_flux_couleur_flux'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceMotif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pres', models.CharField(max_length=150)),
                ('presence', models.CharField(max_length=150)),
                ('jour_travail', models.FloatField()),
                ('couleur_hex_motif_presence', models.CharField(blank=True, max_length=7)),
            ],
            options={
                'ordering': ['pres', 'presence'],
            },
        ),
        migrations.AlterModelOptions(
            name='collecte',
            options={'ordering': ['-date_collecte', '-date_creation']},
        ),
    ]
