# Generated by Django 6.0.1 on 2026-01-30 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_presencemotif_alter_collecte_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencemotif',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presencemotif',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
