# Generated by Django 6.0.1 on 2026-02-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_presencemotif_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
