# Generated by Django 6.0.1 on 2026-04-09 17:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_tache_optional_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectPrev",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("classement", models.CharField(max_length=50)),
                ("infos", models.CharField(blank=True, default="", max_length=255)),
                ("depart", models.TimeField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "agent_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collect_prevs_agent_1",
                        to="core.agent",
                    ),
                ),
                (
                    "agent_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collect_prevs_agent_2",
                        to="core.agent",
                    ),
                ),
                (
                    "agent_3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collect_prevs_agent_3",
                        to="core.agent",
                    ),
                ),
                (
                    "flux",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collect_prevs",
                        to="core.flux",
                    ),
                ),
                (
                    "itineraire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collect_prevs_itineraire",
                        to="core.itineraire",
                    ),
                ),
                (
                    "relais",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collect_prevs_relais",
                        to="core.vehicule",
                    ),
                ),
                (
                    "vehicule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collect_prevs_vehicule",
                        to="core.vehicule",
                    ),
                ),
            ],
            options={
                "db_table": "collect_prev",
                "ordering": ["date", "classement", "id"],
            },
        ),
    ]
